# Enable service catalog
openshift_enable_service_catalog: true

# Enable template service broker (requires service catalog to be enabled, above)
template_service_broker_install: true

# TSB source namespace(s) for loading templates and image streams into the service catalog. 
openshift_template_service_broker_namespaces: ['openshift']

# Force a specific image version to use when pulling the service catalog image
openshift_service_catalog_image_version: v3.11

# Force a specific image version to use when pulling the template service broker image
template_service_broker_version: v3.11

# Force a specific image version to use when pulling the ansible service broker image
ansible_service_broker_image_tag: v3.11

# Force a specific image version to use when pulling the ansible etcd service broker image
ansible_service_broker_etcd_image_tag: latest
